sudo: false
language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- nightly
matrix:
  allow_failures:
  - python: nightly
  include:
  - python: '3.7'
    env: TOXENV=lint
  - python: '3.7'
    env: TOXENV=scan
install: make travis-install
before_script: make travis-before-script
script: make travis-script
after_success: make travis-after-success
deploy:
- provider: pypi
  server: https://upload.pypi.org/legacy/
  user: Andrew.Hawker
  password:
    secure: GD0UFLJEyBYwE52ouQHJDEG8ExwOxSqGPBrUgIsz8VTKE07CtIwc/xQLqoBToqtb4cVoRghEI75oz4VqH91hcP9j3WN3zdXRuRa+Z6DZ0Y9aZoxL637jCYYKeVphHuVxCl0ukZL9AftF8pVlE4xDlorxmxz6xHBQdyTPCRC4HpiqLumehr3FHPNJceR75EDeAjCckWia1yWJXH+1AbSOIYmUqfuUjS7H1vpvNEPvB5wVWiznQGhf09uicyGq91hPtkX6/Ufowr7LmZHF8cufYbRat2GIjdAKuTDo9WoD1mCEZthA1be96+nWz402IPGGUd8bu66RsDVeEDXG8oihT83GEICK2C60CX6fogCNK6/ri2EaiY2H4FkhRSnLTtNTWPoukGsihHV8ZKLwLfH0Fpv0nxXLTjCdKckScSWxyK/9Vq+IL/ydSkNoGjlJVNmj5BWLuQi9eXpe4qRe/dEQ9HpdZY+qLgUjrGfrBPKYr9UgANCoh13hMg3hur5uCORw5IZrEfxIonNbgRBs7lQEUKvufmdKVqw5EajuWlNCHPk1bGLVyCr+qHMjPVinKEbVT5ob6qKAx0SlNKV0M9S3uaXNtmegh9bnwC6mFmJS9xuRwS7I0BQvt5Wsut9+yN+x2DsBRv9z6Jog6MKevmC2XjePPuoR3BxZOWwaxsIoXOc="
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.8"
notifications:
  slack:
    secure: 3OZk8G2/+8BY2c+mLg+YT47JxE7gKwHyFDiH1vQgcyeytMFYmBL1dGMhxQxCT2tL5TzfUfh1qzjP7U6Z7z0gpKkLn/ZagwPr5xQ890CPT4QxSCKEBJMoUs1sgyRiHEwLzlXvdPVsnZx0GQsnfkDwkTqFDm6u2xVp2zn8lSyhKmUi/tZsxWTnnunyB2JkgZhFUNyt4VIY/nbg+RNd3rxX41DwyDTdgV2c5wyW6U/L/rOu7aSafmFQ0lFzi2/c/EWD0XrvooX3aXevvO7WXT8nMow1kXJ6ZKc8GxwD5WkZangwlCCunS9JvzfaJdl2ypk1A40l6x9SnystQz8w6zc84Ixi+/Ys4Xy/9YWXGY+98IjC64cY1aayy0bNbvVwWkUVoS3SjT98nsEsJOlCqhg95FPC8z3I+5aCe72Q7YGWEULQ0vbiaWrQWb2mbE63spLaEqX8m18Qa6Od2mwCmPfCf0MR/w58DSq6z2id3h/OvDIoB2bEHS7V72sr3KRNW0xJA5FIN1E+kKY0a8saPZZAteWlt0UnKV+J0B87YRFnK4xdJV/BZih9Ha5VACibvygN9eyijJTyggTZrFzjpWP9zUkuPkKKn/lW0hT72PPzXKr3WTjA0ZfTXKvEqFWJIvXAab9gaK0UCEoz4VgBaAJQs0O5VRSRaSWb99J+cF47vew=
env:
  global:
  - VIRTUALENV_NO_DOWNLOAD=1
  - secure: fXMbE0m7APqqdXrLOsaXacG4JdhUIcF2thEDc6irRCMjXVCQrglOYGVJv/PwtvkhctwDML/VvSA/DTWK13TkKMNWLq5VjetgGn+mra48nXG5WkS6ckIEUTY/6bnt+4HFXtGmuHnfD55Q6uKSCwYARvWzSTO4+DGqOyZo5jOfzkLRFd83dl/zu14Da6FoZIB1HUUzP/Bokw8lOI5SZLyQhkngQG6TlrzFjjAdvE7xvEhrOdkGFO699gYJPYAjgYnPo4ZegKqHMcPla6UBWY3Nohy5oqWfYxMMWMM8Ey/HrwySHRpyf7ZZr8BHf7wSPcHcG1txkgs7kPegnsNzTb5EEgqEm7g1G5g1zLOfqfBkvU44iVcMkM/oVEQ9aYqtobbCZUzQeGEcgW3RRB9AA/rTXTWzf8xQyxYNjR5xeJiH9MJ7Mz0zYFT9Oof209ECd+SXxEIb99DSN0EyMhi5lJFyQe1hy2oYWDGQVUslkgidLWXtGyxgb2m+B3zlybuZAh2SBpb5Y7jXPhWBnQ6qopAOaQ6Ren3PPvAJ6xLwzCLLzpZVTocA1dbThWl+TmLV15xA8es8Iop83n+vgwqb8hCN5Uy2/OcPQ/FYWMCyJ2UTbE4811UQEJmlml0HxrkeXnI+lFxc6oozeMR9PFCb29ZqT7UknUOn9j/XM9CwQXwpbOY=
  - secure: Tsbn27ppQDhUu8hVZy8kp5Hu88P5cEataSFMLytuj4clHLZd05c6BKhpd3dWz9wHSUwop9Rdtylp1rc/j+3QOoL0n8YUvG5LQvsuNsOiUToWgNrLqueMIb2JVJhm0YpQgK4rzhRpL0gqSCR/Vk4xEJQ72/BciBS1EuSlXP0FufUB1+71MoK3a73LvXaAISfQQpS8re9VSOZ185aQt6NQXUJnu7M8pLC1gKEpyExwR+149t8w10gHzzNSZk53GTR2LQnEfnZk0tap4LygHKkS1bkSJU5EW23YOZ8kRxJZDSa0/oF/TooSaP4ZGb/BK8p6VL9PYc2TuRWd99ufFRbMRM+61oyxRlvBCF/x/klhAcaN+mt56oep5iZN2lh0UmFWZghcQIYPkTvQJ1Z7YrQT7eWrA6+b2pXkBW5eZueoIlQJ960712aoebOi02LaQiJrI3SMrWbsEWoF1GXwfyAuDc97YIsVQaxvYe9Yu/Wj0SX1zVWmbdwxbVajXHitfKi4mksC7DQ5Z369X1+8Dy+VtvO+SP41wR7GzWgaYf/inpLIWPmD9rdeMSWTQRTybjP+SZtVL/ji3JYRb7cnG8wCbA7iEaFWAULCX2z5/bSVF+F3S+SRnuCa6uzaJ1ci7w9Od3vrOzmocio6c13ZSPJ379RqRtJdJi52gMXKjooW/HU=
